name: Docker Image CI - 'langgraph-agent'

on:
  push:
    branches: [ "main" ]
    paths:
      - 'langgraph-agent/*'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'langgraph-agent/*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file langgraph-agent/Dockerfile --tag chainlit_ui:$(date +%s)
