name: LangGraph Agent CI/CD

env:
  AZURE_WEBAPP_NAME: agentcv
  PYTHON_VERSION: '3.11'

on:
  push:
    branches: [ main ]
    paths:
      - 'langgraph-agent/**'
  workflow_dispatch:


jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build langgraph-agent image
        run: |
          docker build -f langgraph-agent/Dockerfile -t agustinst1990/langgraph-agent-chainlit-ui:latest .

      - name: Push langgraph-agent image
        run: |
          docker push agustinst1990/langgraph-agent-chainlit-ui:latest

  deploy:
    name: Azure Web App Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'agustinst1990/langgraph-agent-chainlit-ui:latest'
