# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - agustincvagent

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://cvagent.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4ca5ecd909c4402584ad81c30bf1e18a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_bc7efdbc4654477e8cd7fb52700c84d8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: cvagent.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4ca5ecd909c4402584ad81c30bf1e18a }}/images:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'agustincvagent'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2b6a0395a2794356b4efbf6e9bb157b0 }}
        images: 'cvagent.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4ca5ecd909c4402584ad81c30bf1e18a }}/images:${{ github.sha }}'