name: Pylint

on:
  push:
    branches: [ "main" ]
    paths:
      - 'langgraph-agent/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        make install
    - name: Analysing the 'langgraph-agent' code with pylint
      run: |
        pylint --disable=R,C $(git ls-files './langgraph-agent/*.py')
    - name: Analysing the 'knowledge-graph-ingest' code with pylint
      run: |
        pylint --disable=R,C $(git ls-files './knowledge-graph-ingest/*.py')
